# Generated by Django 4.1.5 on 2023-03-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(max_length=30)),
                ('format', models.CharField(max_length=30)),
                ('measurementUnit', models.CharField(max_length=30)),
                ('detailURL', models.URLField()),
                ('unitPrice', models.IntegerField()),
            ],
        ),
    ]
