# Generated by Django 4.1.5 on 2023-03-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canasta', '0002_supermarket_remove_product_unitprice_sells'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sells',
            name='item',
        ),
        migrations.RemoveField(
            model_name='sells',
            name='supermarket',
        ),
        migrations.AddField(
            model_name='sells',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='canasta.product'),
        ),
        migrations.AddField(
            model_name='sells',
            name='supermarket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='canasta.supermarket'),
        ),
    ]
