# Generated by Django 4.1.5 on 2023-03-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canasta', '0003_remove_sells_item_remove_sells_supermarket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detailURL',
        ),
        migrations.AddField(
            model_name='sells',
            name='detailURL',
            field=models.URLField(default=''),
        ),
    ]
