# Generated by Django 4.1.5 on 2023-03-10 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('canasta', '0005_sells_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sells',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha ultima busqueda'),
        ),
    ]
